### ISSUE TITLE
Map is not rendering

### ISSUE THREAD

**Issue by AlineJo** [halilozel1903/HuaweiMapKitApp#1]
Hello, how are you?

I created my own project, In Huawei dev console, downloaded ag-connect-service file, and changed the app id. Unfortunately,  the map is not rendering (https://drive.google.com/file/d/1KutW6FdLzYYF9hJ_Y4FSzvVWqWr4Zobs/view?usp=sharing) .what could be the issue?

by the way, I enabled both Map kit and Location API. Also, there is these errors displayed in logcat:

`2021-09-21 15:00:34.258 17384-17637/com.marsa.store E/HmsMapKit_TileCache_38: startUrlRequest Identity fail, do not has permission get tile. authResult :6`
```

2021-09-21 15:00:49.986 17384-17563/com.marsa.store E/HmsMapKit_MapDataVersionClient_28: Exception occur
    com.huawei.hms.maps.foundation.client.mac: * * *E*U*S*_*E*I*D
        at com.huawei.hms.maps.foundation.client.mac$maa.b(Unknown Source:25)
        at com.huawei.hms.maps.foundation.client.mab.a(Unknown Source:20)
        at com.huawei.hms.maps.foundation.client.mab.c(Unknown Source:80)
        at com.huawei.hms.maps.foundation.client.mab.a(Unknown Source:88)
        at com.huawei.hms.maps.foundation.client.mab.a(Unknown Source:1)
        at com.huawei.hms.maps.provider.client.dataversion.maa.m(Unknown Source:2)
        at com.huawei.hms.maps.provider.client.dataversion.maa.lambda$VkLWwzu7W690n_qHxpBFU9o7rLI(Unknown Source:0)
        at com.huawei.hms.maps.provider.client.dataversion.-$$Lambda$maa$VkLWwzu7W690n_qHxpBFU9o7rLI.call(Unknown Source:4)
        at com.huawei.hms.maps.foundation.client.mab$maa.a(Unknown Source:3)
        at com.huawei.hms.maps.provider.client.dataversion.maa.e(Unknown Source:28)
        at com.huawei.hms.maps.provider.client.dataversion.maa.d(Unknown Source:4)
        at com.huawei.hms.maps.provider.cache.mac$maa.a(Unknown Source:0)
        at com.huawei.hms.maps.provider.cache.mac$maa.call(Unknown Source:0)
        at mnr.b(Unknown Source:17)
        at mma.a(Unknown Source:14)
        at mnv$mab.run(Unknown Source:6)
        at mmd$maa.run(Unknown Source:9)
        at moh.run(Unknown Source:13)
        at moh.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2021-09-21 15:00:49.993 17384-17563/com.marsa.store E/HmsMapKit_ErrorTraceLogPusher_4: cache error trace log : ErrorTraceLogDTO{ scenario = ACCESS_SERVICE_ERROR', message='6 : REQUEST_DENIED'}
    com.huawei.hms.maps.foundation.client.mac: * * *E*U*S*_*E*I*D
        at com.huawei.hms.maps.foundation.client.mac$maa.b(Unknown Source:25)
        at com.huawei.hms.maps.foundation.client.mab.a(Unknown Source:20)
        at com.huawei.hms.maps.foundation.client.mab.c(Unknown Source:80)
        at com.huawei.hms.maps.foundation.client.mab.a(Unknown Source:88)
        at com.huawei.hms.maps.foundation.client.mab.a(Unknown Source:1)
        at com.huawei.hms.maps.provider.client.dataversion.maa.m(Unknown Source:2)
        at com.huawei.hms.maps.provider.client.dataversion.maa.lambda$VkLWwzu7W690n_qHxpBFU9o7rLI(Unknown Source:0)
        at com.huawei.hms.maps.provider.client.dataversion.-$$Lambda$maa$VkLWwzu7W690n_qHxpBFU9o7rLI.call(Unknown Source:4)
        at com.huawei.hms.maps.foundation.client.mab$maa.a(Unknown Source:3)
        at com.huawei.hms.maps.provider.client.dataversion.maa.e(Unknown Source:28)
        at com.huawei.hms.maps.provider.client.dataversion.maa.d(Unknown Source:4)
        at com.huawei.hms.maps.provider.cache.mac$maa.a(Unknown Source:0)
        at com.huawei.hms.maps.provider.cache.mac$maa.call(Unknown Source:0)
        at mnr.b(Unknown Source:17)
        at mma.a(Unknown Source:14)
        at mnv$mab.run(Unknown Source:6)
        at mmd$maa.run(Unknown Source:9)
        at moh.run(Unknown Source:13)
        at moh.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2021-09-21 15:00:50.001 17384-17563/com.marsa.store W/HmsMapKit_ErrorTraceLogPusher_36: log push is not allow.
2021-09-21 15:00:50.004 17384-17563/com.marsa.store E/HmsMapKit_MapDataVersionCache_21: mapStyleVersion is invalid, start retry...
2021-09-21 15:00:50.012 17384-17384/com.marsa.store E/HmsMapKit_TileCache_4: query mapDataVersion failed!

```

**Comment by halilozel1903** [comment]
How you doin’  @AlineJo 

You should try the project on a Huawei real device or cloud debugging.

https://developer.huawei.com/consumer/en/doc/development/Tools-Guides/cloud-debugging-0000001051084360 

Can you look at this url?

https://stackoverflow.com/questions/67063018/huawei-map-kit-certificates# 

https://stackoverflow.com/questions/63057041/hms-map-kit-problem-huawei-map-doesnt-load

**Comment by AlineJo** [comment]
>
> Thanks for the reply ,
>
im using huawei device. Also, Previously  checked those links



*Yousuf Ali Al-Qasmi.*


*Junior Programmer*

*GSM : +968 920 911 68*

**Comment by halilozel1903** [comment]
Hi @AlineJo , 

I updated the project. The application works. You can pull the final version and try it.

![huaweiMapKitScreen2](https://user-images.githubusercontent.com/22895813/134808750-4aeed138-1d38-452d-a3a7-d1379acb7492.png)
